export const placeholders = [
  "Search",
  "Find",
  "Explore",
  "Discover",
  "Navigate",
  "Locate",
  "Uncover",
  "Investigate",
  "Seek",
  "Hunt",
  "Scan",
  "Probe",
  "Inspect",
  "Examine",
  "Trace",
  "Track",
  "Hunt down",
  "Identify",
  "Spot",
  "Quest",
  "Research",
  "Scour",
  "Pursue",
  "Survey",
  "Retrieve",
  "Fetch",
  "Sift through",
  "Root out",
  "Follow",
  "Delve into",
  "Dig up",
  "Explore",
  "Sift",
  "Investigate further",
  "Search high and low",
  "Explore extensively",
  "Delve deeper",
  "Pursue relentlessly",
  "Track down",
  "Follow the trail",
  "Probe deeply",
  "Scrutinize",
  "Dig into the details",
  "Unearth",
  "Unfold",
  "Inspect closely",
  "Navigate through",
  "Study",
  "Research thoroughly",
  "Unravel",
  "Examine minutely",
  "Scrutinize closely",
  "Follow leads",
  "Interrogate",
];
